name: Generate Star History Chart

on:
  schedule:
    - cron: '0 0 * * 0' # Exécution automatique tous les dimanches à minuit
  workflow_dispatch: # Permet de lancer manuellement depuis l'onglet Actions de GitHub

permissions:
  contents: write

jobs:
  update-star-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Star History SVG
        uses: narayann7/star-history-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repos: ${{ github.repository }}

      - name: Commit & Push updated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update star history chart [skip ci]"
          file_pattern: 'assets/star-history.svg'
